[theme]
primaryColor="#c71717"
backgroundColor="#465849"
secondaryBackgroundColor="#bebfb8"
textColor="#f5f0f0"

[header]
title = "RAG"
logo = "https://media.istockphoto.com/id/1505750815/vector/cyber-cat-portrait-robot-catoon-style-animal-head-icon-design.jpg?s=612x612&w=0&k=20&c=scMm-CsaYA-hIdmsPSwTVt38b1eRtxUlZ9NCndDZzSs="  # Ajouter l'URL de votre premier logo ici
favicon = "https://static.vecteezy.com/system/resources/thumbnails/020/329/376/small/cat-head-kitten-symbol-gaming-cat-logo-elegant-element-for-brand-abstract-icon-symbols-vector.jpg"  # Ajouter l'URL de votre deuxième logo ici